# Generated by Django 3.1.7 on 2021-05-22 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryoptions',
            name='delivery_method',
            field=models.CharField(choices=[('RS', 'Regular Shipping'), ('ES', 'Expedited Shipping'), ('OS', 'Overnight Shipping')], help_text='Required', max_length=255, verbose_name='delivery_method'),
        ),
    ]
