# Generated by Django 3.1.7 on 2021-07-01 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210523_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='country_code',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
